Minor Fixes
GenerateNU/sac pull request #318
Opened 2024-03-05 22:05 UTC by alderwhiteford

Minor fixes to documentation, syntax, and structs

2024-03-05 22:08 UTC, garrettladley requested changes
See backend/src/transactions/club_event.go

2024-03-05 22:08 UTC, garrettladley commented on backend/src/transactions/club_event.go
Error message changed and not using limit & offset anymore?

2024-03-05 22:09 UTC, alderwhiteford commented on backend/src/transactions/club_event.go
I'll fix

2024-03-05 22:10 UTC, alderwhiteford commented on backend/src/transactions/club_event.go
error message is wrong as well lmao. I am tired today

2024-03-11 22:43 UTC, garrettladley approved these changes
LGTM 👏

2024-03-11 23:03 UTC, merged