Minor CLI Fix for Formatting Tests
GenerateNU/sac pull request #321
Opened 2024-03-06 00:23 UTC by alderwhiteford

Feel free to close this PR if you don't want the formatter on tests for some reason

2024-03-06 00:30 UTC, garrettladley requested changes
This might have unintended consequences that cause a regression in other commands. Try splitting into BACKEND_SRC and BACKEND vars to add this feature while maintaining parity

2024-03-06 03:51 UTC, alderwhiteford commented
> This might have unintended consequences that cause a regression in other commands. Try splitting into BACKEND_SRC and BACKEND vars to add this feature while maintaining parity

true true

2024-03-07 00:49 UTC, garrettladley requested changes

2024-03-07 00:49 UTC, garrettladley commented on cli/commands/config.go
> +	BACKEND_SRC_DIR = filepath.Join(ROOT_DIR, "/backend/src")
```suggestion
	BACKEND_SRC_DIR = filepath.Join(BACKEND_DIR, "/src")
```

2024-03-07 00:49 UTC, garrettladley commented on cli/commands/config.go
> +	BACKEND_DIR     = filepath.Join(ROOT_DIR, "/backend/")
```suggestion
	BACKEND_DIR     = filepath.Join(ROOT_DIR, "/backend")
```
nit for consistency

2024-03-07 00:50 UTC, merged