Sac 17 user authentication
GenerateNU/sac pull request #38
Opened 2024-01-21 08:47 UTC by DOOduneye

# Description

[Link to Ticket](https://generatesac.atlassian.net/browse/SAC-17)

Please include a summary of the changes and the related issue. Please also
include relevant motivation, context, and images!

Implemented RBAC with JWT Tokens for access and refresh, 

TODOs:
- token blacklist 
- revocation
- token versioning

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. If they are unit
tests, provide the file name the tests are in. If they are not unit tests,
describe how you tested the change.

No tests yet 

# Checklist

- [ ] I have performed a self-review of my code
- [ ] I have reached out to another developer to review my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] New and existing unit tests pass locally with my changes

2024-01-21 15:57 UTC, alderwhiteford commented on backend/src/controllers/user.go
> +		"message": "success",
do we want to return the user information after login to store in state?

2024-01-21 16:01 UTC, alderwhiteford commented on backend/src/middleware/auth.go
> +	if c.Path() == AuthLoginPath || c.Path() == AuthRefreshPath || c.Path() == AuthLogoutPath {
Register should likely be apart of the this list

2024-01-21 16:04 UTC, alderwhiteford commented on backend/src/controllers/user.go
> +	c.Cookie(auth.CreateCookie("access_token", *accessToken, time.Now().Add(time.Minute*15)))
We might want this to be a bit higher so we aren't constantly refreshing the access token?

2024-01-21 16:08 UTC, alderwhiteford commented on backend/src/middleware/auth.go
> +	if c.Path() == AuthLoginPath || c.Path() == AuthRefreshPath || c.Path() == AuthLogoutPath {
and logged out in a call you should only make if logged in so this should also probably be a protected path

2024-02-01 05:12 UTC, garrettladley requested changes
Goated work @melodyyu754 @DOOduneye 🐐 some nits and conflicts then you're good to merge

2024-02-01 05:12 UTC, garrettladley commented on backend/src/transactions/club.go
> +		return nil, &errors.Error{StatusCode: fiber.StatusInternalServerError, Message: "failed to get admin IDs"}
ik neither of us are the biggest fan of the current state of errors, but for consistency shouldn't this be moved to the errors package and be `&errors.FailedToGetAdminIDs`

2024-02-01 05:12 UTC, garrettladley commented on backend/src/services/user.go
> +	CreateUser(userBody models.CreateUserRequestBody) (*models.User, *errors.Error)
```suggestion
```
for idiomatic order of CRUD

2024-02-01 05:12 UTC, garrettladley commented on backend/src/services/user.go
>  type UserServiceInterface interface {
```suggestion
type UserServiceInterface interface {
	CreateUser(userBody models.CreateUserRequestBody) (*models.User, *errors.Error)
```
for idiomatic order of CRUD

2024-02-01 05:12 UTC, garrettladley commented on backend/src/services/auth.go
> +	// check if user exists
nit: necessary comment?

2024-02-01 05:12 UTC, garrettladley commented on backend/src/server/server.go
> +	clubsID.Get("/", middlewareService.Authorize(types.ClubRead), clubController.GetClub) // TODO: Should you be able to get a club without being logged in? (yes)
TODO resolved or should we open an issue / discussion about this then remove the comment?

2024-02-01 05:12 UTC, garrettladley commented on backend/src/models/user.go
> +	Email    string `json:"email" validate:"required,email"`
```suggestion
	Email    mail.Address `json:"email" validate:"required,email"`
```
similar idea to below, should we use the [stdlib mail package](https://pkg.go.dev/net/mail#Address)? if we do, do we even need to validate email 🤔

2024-02-01 05:12 UTC, garrettladley commented on backend/src/models/membership.go
> +	ClubID uuid.UUID `gorm:"primaryKey" json:"club_id" validate:"required,min=1"`
```suggestion
	ClubID uuid.UUID `gorm:"primaryKey" json:"club_id" validate:"required,uuid4`
```

2024-02-01 05:12 UTC, garrettladley commented on backend/src/models/membership.go
> +	UserID uuid.UUID `gorm:"primaryKey" json:"user_id" validate:"required,min=1"`
```suggestion
	UserID uuid.UUID `gorm:"primaryKey" json:"user_id" validate:"required,uuid4"`
```

2024-02-01 05:12 UTC, garrettladley commented on backend/src/models/membership.go
> +type Membership struct {
for logical organization, should the id be on the line above the pointer to the corresponding entity?

2024-02-01 05:12 UTC, garrettladley commented on backend/src/models/membership.go
> +func (Membership) TableName() string {
do we need or is it fine if gorm just auto gens the table name?

2024-02-01 05:12 UTC, garrettladley commented on backend/src/models/club.go
> +func (c *Club) AfterCreate(tx *gorm.DB) (err error) {
huuuuuge! good stuff @melodyyu754 @DOOduneye 👏

2024-02-01 05:12 UTC, garrettladley commented on backend/src/middleware/middleware.go
> +	Authorize(requiredPermissions ...types.Permission) func(c *fiber.Ctx) error
good usage of variadics 👏

2024-02-01 05:12 UTC, garrettladley commented on backend/src/middleware/club.go
> +func ContainsUUID(uuids []uuid.UUID, targetUUID uuid.UUID) bool {
can we replace with [slices.Contains](https://pkg.go.dev/slices#Contains)

2024-02-01 05:12 UTC, garrettladley commented on backend/src/middleware/auth.go
> +func containsPermission(permissions []types.Permission, targetPermission types.Permission) bool {
can we replace with [slices.Contains](https://pkg.go.dev/slices#Contains)

2024-02-01 05:12 UTC, garrettladley commented on backend/src/middleware/auth.go
> +	// check if token is blacklisted
is this a necessary comment?

2024-02-01 05:12 UTC, garrettladley commented on backend/src/auth/tokens.go
> +func IsBlacklisted(token string) bool {
would mark with a TODO or open an issue (prob both)

2024-02-01 05:12 UTC, garrettladley commented on backend/src/auth/tokens.go
> +		Expires:  time.Now().Add(-time.Hour),
Same as above

2024-02-01 20:35 UTC, garrettladley commented on backend/src/auth/tokens.go
> +			ExpiresAt: time.Now().Add(time.Minute * 15).Unix(),
like how we configure auth secrets

2024-02-01 20:38 UTC, garrettladley commented on backend/src/middleware/club.go
> +func ContainsUUID(uuids []uuid.UUID, targetUUID uuid.UUID) bool {
<img width="479" alt="Screenshot 2024-02-01 at 3 38 44 PM" src="https://github.com/GenerateNU/sac/assets/92384606/8cd43283-10fa-4106-9a94-61830bb62b23">

2024-02-01 20:39 UTC, garrettladley commented on backend/src/auth/tokens.go
> +		Expires:  time.Now().Add(-time.Hour),
was talking about making it configurable, that actually doesn't apply here after second thought

2024-02-01 20:42 UTC, garrettladley commented on backend/src/models/membership.go
> +type Membership struct {
like this 
```suggestion
type Membership struct {
	Model

	ClubID uuid.UUID `gorm:"primaryKey" json:"club_id" validate:"required,min=1"`
	Club *Club `gorm:"constraint:OnUpdate:CASCADE,OnDelete:CASCADE;" json:"-" validate:"-"`

	UserID uuid.UUID `gorm:"primaryKey" json:"user_id" validate:"required,min=1"`
	User *User `gorm:"constraint:OnUpdate:CASCADE,OnDelete:CASCADE;" json:"-" validate:"-"`

	Type MembershipType `gorm:"type:varchar(255);default:member" json:"membership_type" validate:"required,max=255"`
}
```

2024-02-02 02:42 UTC, garrettladley commented on config/local.yml
> +  accesstoken: g(r|##*?>\Qp}h37e+,T2
```suggestion
  access_token: g(r|##*?>\Qp}h37e+,T2
```

2024-02-02 03:38 UTC, merged