Major & College and Tags Page Lo-fi
GenerateNU/sac pull request #392
Opened 2024-03-18 01:42 UTC by in-mai-space

# Description

[Link to Ticket](insert the link to your ticket inside the parenthesis here)

Lo-fi pages for major & college, and tags page with multi-select component. Fix for wordmark component to take into color.

# How Has This Been Tested?

No tests.

# Checklist

- [x] I have performed a self-review of my code
- [x] I have reached out to another developer to review my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] New and existing unit tests pass locally with my changes

2024-03-21 19:08 UTC, DOOduneye reviewed
minor nits, great job!

2024-03-21 19:08 UTC, DOOduneye commented on frontend/sac-mobile/app/(auth)/_components/tag-form.tsx
> +let allTags: string[] = [];
should be in a function and possibly a utility if reused or if it's functionality that can be generalized should be generalized

2024-03-21 19:08 UTC, DOOduneye commented on frontend/sac-mobile/app/(auth)/_layout.tsx
> +                name="tags"
user interests would be a better name

2024-03-21 19:08 UTC, DOOduneye commented on frontend/sac-mobile/app/(auth)/login.tsx
> +                        <Wordmark textColor="text-white" />
instead of taking a specific color which is too granular, name specific types such as primary, secondary, default

2024-03-21 19:08 UTC, DOOduneye commented on frontend/sac-mobile/package-lock.json
delete this file

2024-03-22 18:41 UTC, garrettladley requested changes
blown away by the demo earlier this week @akshayd2020 & @in-mai-space 🤯 !! keep up the great work!

echoing @DOOduneye's comments and the CodeQL comments about unused variables/imports

2024-03-25 02:02 UTC, closed without merging