fix: events overhaul
GenerateNU/sac pull request #745
Opened 2024-05-07 03:14 UTC by garrettladley

2024-05-07 17:32 UTC, alderwhiteford commented on backend/entities/events/base/service.go
> +func (e *EventService) GetEvent(eventID string) (models.Event, *errors.Error) {
lmao didn't realize GetEvent was returning an array before

2024-05-07 17:32 UTC, alderwhiteford commented on backend/entities/events/base/service.go
> +	if body.IsSeries {
fuck yeah

2024-05-07 17:37 UTC, alderwhiteford commented on backend/entities/events/base/service.go
> +	for index := 0; index < *numOccurences; index++ {
just curious, have you tested this?

2024-05-07 17:37 UTC, alderwhiteford commented on backend/entities/models/event.go
> +	IsDraft    bool `json:"is_draft" validate:"required"`
MASSIVE

2024-05-07 17:40 UTC, alderwhiteford commented on backend/protos/recurrence.go
> +func (r *Recurrence) MarshallBinary() (data []byte, err error) {
this is dope af

2024-05-07 17:42 UTC, alderwhiteford commented
One small comment, we may want to have a const variable that we can hard set a termination date if people try to set something beyond it

2024-05-08 01:26 UTC, garrettladley commented on backend/entities/events/base/service.go
> +	for index := 0; index < *numOccurences; index++ {
not yet, everything still a wip

2024-05-12 04:01 UTC, DOOduneye requested changes
LGTM! Amazing work with reimagining events

2024-05-12 20:10 UTC, garrettladley commented on backend/config/calendar.go
> +	MaxTerminationDate time.Time
since imo it is more of a config value than a constant. bumping the max termination date shouldn't require a code change, just updating the config.

2024-05-12 20:31 UTC, DOOduneye commented on backend/config/calendar.go
> +	MaxTerminationDate time.Time
but doesn't that mean we'd have to change it every year? it's just a date value i'm still not sure it needs to be configurable or like it makes sense with all the other configuration values we have

2024-05-12 20:43 UTC, garrettladley commented on backend/config/calendar.go
> +	MaxTerminationDate time.Time
how is a constant any different than what we currently have? should this be configurable by the admin dashboard? if so, how would it be stored? db?

2024-05-13 01:10 UTC, garrettladley commented
running into issues mapping structs with fields of type time.Time to other structs with time.Time.
function [`utilities.Map`](https://github.com/GenerateNU/sac/blob/main/backend/utilities/manipulator.go#L8). Opened issue [here](https://github.com/go-viper/mapstructure/issues/20)

2024-05-17 03:59 UTC, merged