dashboard: form build out with validation
GenerateNU/sac pull request #799
Opened 2024-05-14 16:52 UTC by in-mai-space

# Description

[Link to Ticket](https://trello.com/c/X61KYxfx/11-form-submission-build-out-dashboard)

An example of handling forms in dashboard with shadcn components (input, button, select, multiselect).

# How Has This Been Tested?

No tests.

# Checklist

- [x] I have performed a self-review of my code
- [x] I have reached out to another developer to review my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] New and existing unit tests pass locally with my changes

2024-05-17 01:41 UTC, garrettladley reviewed
Good stuff @in-mai-space ! Once you resolve those merge conflicts we should be good to go 😃

2024-05-17 11:22 UTC, alderwhiteford commented on frontend/dashboard/src/app/page.tsx
> +        <Controller
good use of controller

2024-05-17 11:22 UTC, alderwhiteford commented on frontend/dashboard/src/app/page.tsx
> +              {errors.firstName && <p className="mt-1 text-sm text-red-500">{errors.firstName.message}</p>}
we can work out error states in the future

2024-05-17 11:25 UTC, alderwhiteford commented on frontend/dashboard/src/app/page.tsx
> +  formSchema.parse(data);
you can pass the schema as a "resolver" to the useForm hook. 

useForm({
    resolver: zodResolver(formSchema),
  })

2024-05-17 11:25 UTC, alderwhiteford commented on frontend/dashboard/src/app/page.tsx
> +  formSchema.parse(data);
This will automatically trigger and error / success before hitting the onSubmit

2024-05-17 11:30 UTC, alderwhiteford commented on frontend/dashboard/src/app/page.tsx
> +} = useForm<FormData>();
Set the mode to be on onTouched so that the user receives live feedback

https://react-hook-form.com/docs/useform#mode

2024-05-17 11:32 UTC, alderwhiteford commented on frontend/dashboard/src/app/page.tsx
> +} = useForm<FormData>();
React hook form recommends using "default values"

https://react-hook-form.com/docs/useform#defaultValues

2024-05-17 11:37 UTC, alderwhiteford requested changes
Fantastic work! Just some minor tweaks before we are good to merge

2024-05-17 15:07 UTC, DOOduneye requested changes
Minor nits, Looks great otherwise!

2024-05-17 15:07 UTC, DOOduneye commented on frontend/dashboard/src/app/page.tsx
> +const formSchema = z.object({
speaking on using the lib based schemas, we can still use the validation we were using in the controllers in this by using refine:

const formSchema = z.object({
  firstName: z.string()
    .min(2, "First name must be at least 2 characters")
    .refine(value => /^[a-zA-Z]+$/.test(value), {
      message: "First name can only contain alphabetic characters",
    }),
  lastName: z.string()
    .min(2, "Last name must be at least 2 characters")
    .refine(value => /^[a-zA-Z]+$/.test(value), {
      message: "Last name can only contain alphabetic characters",
    }),
  email: z.string()
    .email("Please enter a valid email")
    .refine(value => /^[a-zA-Z]+\.[a-zA-Z]@northeastern\.edu$/.test(value), {
      message: "Please enter your Northeastern email",
    }),
  college: collegeEnum.refine(value => value !== undefined, {
    message: "Please select a college",
  }),
  interests: z.array(z.object({
    label: z.string(),
    value: z.string(),
  })).nonempty("At least one interest is required"),
});

2024-05-17 15:07 UTC, DOOduneye commented on frontend/dashboard/src/app/page.tsx
> +  const onSubmit = (data: FormData) => {
you shouldn't need to parse the zod data anymore as you're using a zod resolver

2024-05-17 15:07 UTC, DOOduneye commented on frontend/dashboard/src/app/page.tsx
> +  defaultValues: {
do we need this default value?

2024-05-17 15:25 UTC, in-mai-space commented on frontend/dashboard/src/app/page.tsx
> -import Image from "next/image";
Yeh I think so, just like an example of handling form. I don't think we gonna modify users' info.

2024-05-17 15:26 UTC, DOOduneye commented on frontend/dashboard/src/app/page.tsx
> -import Image from "next/image";
Sounds good!

2024-05-19 20:57 UTC, DOOduneye approved these changes

2024-05-23 02:23 UTC, garrettladley approved these changes
LGTM @in-mai-space

2024-05-23 02:23 UTC, merged