feat: navbar & club info tag component
GenerateNU/sac pull request #923
Opened 2024-05-27 14:48 UTC by in-mai-space

# Description

[Navbar](https://trello.com/c/kIm2kRQm/16-mobile-navbar-component-fe)
[Club info tag](https://trello.com/c/z7LTqq3C/26-mobile-club-info-tag-component-fe)

Navbar and club info tag component.

# How Has This Been Tested?

No tests.

# Checklist

- [x] I have performed a self-review of my code
- [x] I have reached out to another developer to review my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] New and existing unit tests pass locally with my changes

2024-05-27 18:58 UTC, alderwhiteford commented on frontend/mobile/assets/svg/calendar.svg
we should be able to pull these from an icons library. I believe that we decided on fontawesome

2024-05-27 19:00 UTC, alderwhiteford commented on frontend/mobile/components/club-recruitment-info.tsx
@TylerSchaefer4 do we want to host our components beneath design-system?

2024-05-27 23:45 UTC, garrettladley commented on frontend/mobile/assets/svg/calendar.svg
+1

2024-05-27 23:46 UTC, garrettladley commented on frontend/mobile/app/(app)/(tabs)/_layout.tsx
@in-mai-space could we resolve the errors and warnings in this file?

2024-05-27 23:47 UTC, garrettladley commented on frontend/mobile/components/club-recruitment-info.tsx
same idea here, could we resolve lint warnings? i believe we can ignore inline styles warnings

2024-05-27 23:48 UTC, garrettladley requested changes
some nits and looking for @TylerSchaefer4's feedback. keep up the great work @in-mai-space 👑

2024-05-27 23:50 UTC, TylerSchaefer4 commented on frontend/mobile/components/club-recruitment-info.tsx
> +    const RecruitmentItem = ({icon, title, text}: RecruitmentItemProps) => {
Piggy backing off the lint warning, define `RecruitmentItem` as it's own component in it's own file and then import it to use here

2024-05-28 19:52 UTC, alderwhiteford commented on frontend/mobile/app/(app)/(tabs)/_layout.tsx
> +                    borderTopColor: '#00000066',
avoid hardcoding colors. Either use black or add this to the color theme config

2024-05-29 04:56 UTC, merged